- name: Obtenir la version du firmware sur les switches Aruba
  hosts: Switches_Aruba
  gather_facts: no
  tasks:
    - name: Exécuter la commande show version via SSH
      command: show version
      register: output
      ignore_errors: yes

    - name: Afficher la sortie de la commande
      debug:
        var: output.stdout_lines
